import Head from 'next/head'
import { AppProvider } from '../src/components/context/context';
import Footer from '../src/components/global/Footer'
import Header from '../src/components/global/Header'
import ProductsGrid from '../src/components/products/ProductsGrid';

import { HEADER_DATA_ENDPOINT, PRODUCT_DATA_ENDPOINT } from '../src/utils/endpoints';

export default function Cart({dataMenu}) {

  const { header } = dataMenu;

  return (
    <>
      <Head>
        <title>Cart Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <AppProvider>
        <Header data={header}/>
          <div>
            <h1>Cart page</h1>
          </div>
        <Footer />
      </AppProvider>
    </>
  )
}

export async function getStaticProps() {
  const reqMenu = await fetch(HEADER_DATA_ENDPOINT);
  const { data: dataMenu } = await reqMenu.json();



  return {
    props: {
      dataMenu: dataMenu || {}
    },
    revalidate: 5
  }

}